language: python
python:
    - 3.4
virtualenv:
    system_site_packges: true
before_isntall:
    - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install:
    - pip install -r requirements.txt
script: nosetests
