language: python
python:
    - "3.4_with_system_site_packages"
before_isntall:
    - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
install: "pip install -r requirements.txt"
script: nosetests
