language: python
python:
    - 3.4
virtualenv:
    system_site_packges: true
before_isntall:
    - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
    - pip install -r requirements.txt --use-mirrors
script: nosetests
