language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
before_install:
    - sudo apt-get install -qq python-numpy python-scipy
install:
    # - python setup.py install # Fails because of scipy/travis crap
    - pip install shapely geopy sklearn
# command to run tests
script: nosetests
