# baidu:
#     api_key:
#     scheme: http
#     proxies:

# ignfrance:
#     api_key:
#     username:
#     password:
#     referer:
#     domain:
#     scheme:
#     timeout:
#     proxies:
#     geocode:
#         query_type: 'StreetAddress'
#         maximum_responses: 25
#         is_freeform: False
#         filtering:
#         exactly_one: False
#         timeout:
#     reverse:
#         reverse_geocode_preference: ['StreetAddress']
#         maximum_responses: 25
#         filtering:
#         exactly_one: False
#         timeout:

# geonames:
#     country_bias:
#     username:
#     timeout:
#     proxies:
#     geocode:
#         exactly_one: False

# photon:
#     format_string: "%s"
#     scheme: https
#     timeout:
#     proxies:
#     domain: photon.komoot.de
#     geocode:
#         exactly_one: False
#         timeout:
#         location_bias:
#         language:
#         osm_tag:

# bing:
#     api_key:
#     format_string: "%s"
#     scheme: 'https'
#     timeout:
#     proxies:

# navidata:
#     api_key: # None is OK for non-commercial purposes
#     domain: api.navidata.pl
#     proxies:
#     geocode:
#         exactly_one: False
#         timeout:
#     reverse:
#         exactly_one: False
#         timeout:

# geocodefarm:
#     api_key:
#     format_string: "%s"
#     proxies:
#     geocode:
#         exactly_one: False
#     reverse:
#         exactly_one: False

# google:
#     api_key:
#     domain: maps.googleapis.com # e.g. maps.google.co.uk for a UK bias
#     scheme: https
#     client_id:
#     secret_key:
#     proxies:
#     geocode:
#         exactly_one: False
#         timeout:
#         bounds:
#         region:
#         components:
#             route:
#             locality:
#             adminstrative_area:
#             postal_code:
#             country:
#         language:
#         sensor: False
#     reverse:
#         exactly_one: False
#         timeout:
#         language:
#         sensor: False

# arcgis:
#     username:
#     password:
#     referer:
#     token_lifetime:
#     scheme:
#     timeout:
#     proxies:
#     geocode:
#         exactly_one: False
#     reverse:
#         distance: 1000

# geocoderdotus:
#     username:
#     password:
#     format_string: "%s"
#     timeout:
#     proxies:
#     geocode:
#         exactly_one: False

nominatim:
    format_string: "%s"
    view_box:
    country_bias:
    proxies:
    timeout:
    domain: nominatim.openstreetmap.org
    scheme: https
    user_agent:
    geocode:
        exactly_one: False
        addressdetails: True
        language:
        geometry:
    reverse:
        exactly_one: False
        language:

openmapquest:
    api_key: # No API key is needed by the Nominatim-based platform
    format_string: "%s"
    scheme: https
    timeout:
    proxies:
    user_agent:
    geocode:
        exactly_one: False

# liveaddress:
#     auth_id:
#     auth_token:
#     candidates: 10
#     scheme: https
#     timeout:
#     proxies:
#     user_agent:
#     gecode:
#         exactly_one: False

# placefinder:
#     consumer_key:
#     consumer_secret:
#     timeout:
#     proxies:
#     geocode:
#         exactly_one: False
#         min_quality: 0
#         reverse: False # NOTE: YahooPlaceFinder does not have a reverse method
#         valid_country_codes:
#         with_timezone: True

# opencage:
#     api_key:
#     domain: api.opencagedata.com
#     scheme: https
#     timeout:
#     proxies:
#     user_agent:
#     geocode:
#         language:
#         bounds:
#         country:
#         exactly_one: False
#         timeout:
#     reverse:
#         language:
#         exactly_one: False
#         timeout:

# # NOTE: not a traditional geocoder
# what3words:
#     api_key:
#     format_string: "%s"
#     scheme: https
#     timeout:
#     proxies:
#     geocode:
#         lang: en
#         exactly_one: True # Has no effect for this geocoder
#         timeout:
#     reverse:
#         lang: en
#         exactly_one: True # Has no effect for this geocoder
#         timeout:

# databc:
#     scheme: https
#     timeout:
#     proxies:
#     user-agent:
#     geocode:
#         max_results: 25
#         set_back: 0
#         location_descriptor: rooftopPoint
#         exactly_one: False

# yandex:
#     api_key:
#     lang: 'ru_RU' # Default
#     timeout:
#     proxies:
#     geocode:
#         exactly_one: False
#     reverse:
#         exactly_one: False
